kind: Service
apiVersion: v1
metadata:
  name: APP_NAME-service
  labels:
    app: APP_NAME
spec:
  selector:
    app: APP_NAME
  ports:
  - name: dnsport
    nodePort: 30053
    port: 53
    protocol: UDP
    targetPort: 53
  type: NodePort
