apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: APP_NAME
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: APP_NAME
  minReplicas: APP_REPLICA
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
